FROM tomcat:7.0.65-jre7
MAINTAINER "manjula rathnayaka"

ADD settings.xml /usr/local/tomcat/conf/
ADD tomcat-users.xml /usr/local/tomcat/conf/

ADD *.war /usr/local/tomcat/webapps/

CMD ["catalina.sh", "run"]
