apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-controller
spec:
  replicas: 1
  selector:
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-server
        image: "kasun/af_tomcat:latest"
        ports:
        - containerPort: 8080
          hostPort: 9300
