apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-controller
spec:
  replicas: 1
  selector:
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: git-sync
        image: "roshancd/git-sync:latest"
        volumeMounts:
        - name: webappdata
          mountPath: /git
        env:
        - name: GIT_SYNC_REPO
          value: http://github.com/roshancd/kube-test.git
        - name: GIT_SYNC_DEST
          value: /git
      - name: tomcat-server
        image: "roshancd/kube:latest"
        volumeMounts:
        - name: webappdata
          mountPath: /usr/local/data
        ports:
        - containerPort: 8080
        command: ["catalina.sh", "run"]
      volumes:
      - name: webappdata
        emptyDir: {}
