apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-controller
spec:
  replicas: 1
  selector:
    app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-server
        image: "roshancd/kube:latest"
        ports:
        - containerPort: 8080
          hostPort: 8181
        command: ["catalina.sh", "run"]
        volumeMounts:
        - name: my-volume
          mountPath:    /usr/local/data/
      volumes:
      - name:   my-volume
        gitRepo:
            repository: "https://github.com/roshancd/kube-test.git"
            revision: "HEAD"
